name: Sender Workflow (api-specs-test org)

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in ballerina-library-test org
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CROSS_REPO_PAT }}" \
            https://api.github.com/repos/ballerina-library-test/ballerina-library/dispatches \
            -d '{
              "event_type": "trigger-from-api-specs-test",
              "client_payload": {
                "sender": "api-specs-test/api-specs"
              }
            }'
